### ISSUE TITLE
List of ToDos towards GoLive - Sept 17/18th 2018

### ISSUE THREAD

**Issue by tony-shannon** [LeedsCC/Helm_PHR#5]
General
- [x] SSL cert sort
- [ ] move to HSCN with VPN access for RT, CC
- [x] load Helm website with links to login page & vice versa 

PulseTile
- [x] modify the PulseTile logic to generate the Authorization: Bearer{space} {jwt value} header on every /api request - see comment below https://github.com/LeedsCC/Helm_PHR/issues/5#issuecomment-421958286
- [x] Kirill investigating login related main.js auth error/bug , see comment below https://github.com/LeedsCC/Helm_PHR/issues/5#issuecomment-422077643
- [ ] If no data from Discovery/openEHR ,  ie the return array is empty , the data tables for Probs/Meds/All,Vaccs need to say "No information available" (Top 3 things should already ask user to add data is empty initially)
- [ ] If click on (?) to start tour; 2 things happen - 1) go to Patient Summary screen first in the detailed record, then 2) the same click launches the tour from there
- [x] Add T&C modal on login (inc Click4Assistance) - see html below 
https://github.com/LeedsCC/Helm_PHR/issues/5#issuecomment-422015362
- [x] Check Demographics & Patient Profile alignment ,see comment https://github.com/LeedsCC/Helm_PHR/issues/5#issuecomment-422179738
- [x] Oleg working on Helm branded HTML Sign in Page - 
- [x] Simon to make Helm login page static
- [x] no favicon
- [x] Title Bar in Browser needs to say myHelm
- [x] Add Click4Assist script to index page?
- [ ] In profile, prefix PHR with "User Role:" and prefix "Date of Birth:" to date  
- [ ] In profile, invoke user.dateOfBirth value and convert from UTC to regular date
- [x] In patient summary settings cog, remove "List Only" and rename "Full view" to "Headings + List" and rename "Only Preview" to "Headings"
- [ ] Add feeds to Patient Summary view only -set Feeds on as Default view in Cog wheel Settings
- [ ] When side bar menu is expanded, menu button should read 'X Close'
- [ ]  ~~~~ 
- [ ] Add home button to top left as a configurable option alongside back button

QEWD
- [x] hook in Discovery Demographics
- [ ] set up new EHR on EtherCIS when user signs up
- [ ] finalise the Discovery APIs -ie trigger writes to EtherCIS on login & add Vaccinations API
- [ ]  ~~ Pen test non crit ~~
- [ ] switch to username > email for login to improve security
- [ ] add LeedsCC RSS feed https://www.leeds-live.co.uk/news/?service=rss on pt signup (?sec risk if API accessible?)
- [ ] swap top 3 things over to openEHR API
- [ ] check Date in Summary table - is from original source, not EtherCIS persistence date
- [ ] change to "GP" in Summary table - if data from DDS
- [ ] change to "EtherCIS via Discovery" in Source Detail if data from DDS
- [ ] was able to login without username/pwd challenge - related to openID timeout (?CitzenIDrule 60min?)
- [ ] ~~~~
- [ ] Allergies entries duplicated? to monitor
- [ ] limit login to 1 device at time
- [ ] HTML escape Top 3 things data returned to PulseTile
- [ ] HTML escape all data returned to PulseTile

EtherCIS
- [x] setting up EtherCIS as a service, so can re started automatically
- [x] most of the admin work to be doable without needing teamviewer nor webmin
- [ ] staging env to be setup

**Comment by tony-shannon** [comment]
T&C copy of

[Helm Terms and Conditions 180914 Final as HTML.txt](https://github.com/LeedsCC/Helm_PHR/files/2388721/Helm.Terms.and.Conditions.180914.Final.as.HTML.txt)

**Comment by tony-shannon** [comment]
> Comment re PulseTile Authorisation issue above
> 
> > Currently PiulseTile holds the JWT as a cookie - which is OK,,,,but it assumes that all that's then needed for security is that the browser sends the JWT as the cookie - which happens automatically in the browser.  HOWEVER - that's insufficient as all it requires is someone to get hold of a JWT and they can spoof access.  The trick is for PulseTile to ALSO add the JWT as a bearer token in an Authorization header   ie Authorization: Bearer JWT-value.   As a malicious user can't know what the JWT will be, they can't spoof a page that also generates the correct Authorization token.    What I need to then add to the back-end is a check for not only the cookie, but also the Authorization header and only allow access if BOTH have the same JWT value
> > So - need to modify the PulseTile logic to generate the Authorization header on every /api request

Rob has made change to QEWD side to handle this

**Comment by tony-shannon** [comment]
![image](https://user-images.githubusercontent.com/939996/45635530-1c2ad100-ba9d-11e8-8b34-ecd67dd34c5b.png)

**Comment by tony-shannon** [comment]
Check Demographics v Pt Profile 
![image](https://user-images.githubusercontent.com/939996/45651649-eea84c80-bac9-11e8-88cc-52949c03f5e4.png)

**Comment by tony-shannon** [comment]
> main.js auth error
> The provided value 'application/rss+xml' is not a valid enum value of type XMLHttpRequestResponseType.
> t.send @ main.js:1
> ![image](https://user-images.githubusercontent.com/939996/45635530-1c2ad100-ba9d-11e8-8b34-ecd67dd34c5b.png)

Rob has explained that patient banner data is coming from DDS, while the patient profile info is coming from openID service, so this mismatch is down to test data and will be tidied earlier

**Comment by tony-shannon** [comment]
> main.js auth error
> The provided value 'application/rss+xml' is not a valid enum value of type XMLHttpRequestResponseType.
> t.send @ main.js:1
> ![image](https://user-images.githubusercontent.com/939996/45635530-1c2ad100-ba9d-11e8-8b34-ecd67dd34c5b.png)

On discussion with Kirill the console error there is related to the feedsAPI , but is not critical at this time, so we will park this one

NB there is a separate but related issue here about Infinite Spinner/ Loading State.. see here
https://github.com/PulseTile/PulseTile-React-Core/issues/223

**Comment by PhilBarrett** [comment]
Remaining work separated out into separate issues and moved into the backlog
